name: Release Action

on:
  release:
    types:
      - published
      - created
      - edited
      - released

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_COMMIT }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_COMMIT}}

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Update Release

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: '3.x'
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update RELEASES.MD
        uses: vonage/generate-release-log@1.0.2

      - name: Commit release
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git remote -v
          git add RELEASES.md
          git commit -m "chore: updated release log"
          git push --force-with-lease
